version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd $APP_NAME
      - echo Installing dependencies
      - npm i
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests...
      - CI=true npm test
      - echo Building Docker Image...
      - docker build -t $APP_NAME:latest .
      - docker tag $APP_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest