version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    depends_on:
      - backend
    container_name: zgallery-frontend
    ports:
    - 3000:3000
    volumes:
    - ../zgallery-frontend:/opt/zgallery-frontend
    stdin_open: true
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: zgallery-backend
    ports:
      - 5000:3000
    volumes:
      - ../zgallery-backend:/opt/zgallery-backend
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}