FROM node:lts

ENV app_path /opt/zgallery-frontend

RUN mkdir -p ${app_path}

VOLUME ${app_path}

EXPOSE 3000

COPY entrypoint-front.sh .

RUN chmod u+x entrypoint-front.sh

ENTRYPOINT ["./entrypoint-front.sh"]
