AWSTemplateFormatVersion: "2010-09-09"
Description: 'Deploys ZGallery ASG and Instances'

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  RandomId:
    Type: String
    Default: start

Resources:
  ZGalleryInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'zgallery-instance-sg'
      GroupDescription: 'Allow http'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  ZGalleryLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ZGalleryInstanceSecurityGroup
      IamInstanceProfile: !Ref ZGalleryInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo "This is for rolling update ${RandomId}"
          yum update -y
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v -c ascending -s ${AWS::StackId} -r ZGalleryLaunchConfiguration --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ZGalleryASG --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          ascending:
            - configure-instance
            - install-docker
            - run-zgallery-frontend
            - run-zgallery-backend
        configure-instance:
          packages:
            yum:
              python3-pip: []
          commands:
            install-awscli:
              command: pip3 install awscli
            set-put-hop-limit:
              # This is for authentication requests using Metadata v2 can reach docker containers
              command: !Sub |
                aws ec2 modify-instance-metadata-options \
                  --instance-id $(curl http://169.254.169.254/latest/meta-data/instance-id) \
                  --http-endpoint enabled \
                  --http-put-response-hop-limit 2 \
                  --region ${AWS::Region}
        install-docker:
          packages:
            yum:
              docker: []
          services:
            sysvinit:
              docker:
                enabled: "true"
                ensureRunning: "true"
        run-zgallery-frontend:
          commands:
            ecr-login:
              command: !Sub "$(aws ecr get-login --region ${AWS::Region} --no-include-email)"
            start-zgallery-frontend:
              command: !Sub |
                docker run -d -p 5000:5000 \
                    --log-driver=awslogs \
                    --log-opt awslogs-region=${AWS::Region} \
                    --log-opt awslogs-group=zgallery-frontend \
                    --log-opt awslogs-create-group=true \
                    ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/zgallery-frontend
        run-zgallery-backend:
          commands:
            ecr-login:
              command: !Sub "$(aws ecr get-login --region ${AWS::Region} --no-include-email)"
            start-zgallery-backend:
              command: !Sub |
                docker run -d -p 3000:3000 \
                    --log-driver=awslogs \
                    --log-opt awslogs-region=${AWS::Region} \
                    --log-opt awslogs-group=zgallery-backend \
                    --log-opt awslogs-create-group=true \
                    ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/zgallery-backend

  ZGalleryASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs
        Ref: 'AWS::Region'
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 2
      LaunchConfigurationName: !Ref ZGalleryLaunchConfiguration
      TargetGroupARNs:
        - !ImportValue zgallery-target-group
        - !ImportValue zgallery-backend-target-group
      Tags:
        - Key: app
          PropagateAtLaunch: true
          Value: zgallery
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        WaitOnResourceSignals: true

  ZGalleryInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ZGalleryInstanceRole

  ZGalleryInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      Policies:
        - PolicyName: ZGalleryInstanceRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:ModifyInstanceMetadataOptions
                  - ec2:DescribeTags
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:*
                Resource:
                 - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/zgallery-backend
                 - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::zgallery.pictures
                  - !Sub arn:aws:s3:::zgallery.pictures/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ssm:DescribeAssociation
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:GetDocument
                  - ssm:DescribeDocument
                  - ssm:GetManifest
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:ListAssociations
                  - ssm:ListInstanceAssociations
                  - ssm:PutInventory
                  - ssm:PutComplianceItems
                  - ssm:PutConfigurePackageResult
                  - ssm:UpdateAssociationStatus
                  - ssm:UpdateInstanceAssociationStatus
                  - ssm:UpdateInstanceInformation
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ec2messages:AcknowledgeMessage
                  - ec2messages:DeleteMessage
                  - ec2messages:FailMessage
                  - ec2messages:GetEndpoint
                  - ec2messages:GetMessages
                  - ec2messages:SendReply
                Resource:
                  - '*'
