AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the Stack for ZGallery Webapp'

Resources:
  ZGalleryALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'zgallery-alb-sg'
      GroupDescription: 'Allow http for ALB'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ZGalleryERC:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'zgallery-backend'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 10,
              "description": "Keep 3 images only",
              "selection":
              {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
            "action": { "type": "expire" }
            }]
          }

  ZGalleryALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: zgallery-alb
      SecurityGroups:
        - !GetAtt ZGalleryALBSecurityGroup.GroupId
      Subnets:
        - subnet-0446e35e
        - subnet-5de38815
        - subnet-81e07be7

  ZGalleryALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ZGalleryALBTargetGroup
      LoadBalancerArn: !Ref ZGalleryALB
      Port: 80
      Protocol: HTTP

  ZGalleryALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: zgallery-alb-tg
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-f4c2ec92
