AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the Stack for ZGallery Webapp'

Resources:
  ZGalleryDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      Name: zgallery.esuarez.info
      HostedZoneName: esuarez.info.
      Comment: DNS name for ZGallery
      TTL: 300
      ResourceRecords:
        - !GetAtt ZGalleryALB.DNSName

  ZGalleryBackendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      Name: backend.zgallery.esuarez.info
      HostedZoneName: esuarez.info.
      Comment: DNS name for ZGallery Backend Service
      TTL: 300
      ResourceRecords:
        - !GetAtt ZGalleryALB.DNSName

  ZGalleryDevBackendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      Name: backend.dev.zgallery.esuarez.info
      HostedZoneName: esuarez.info.
      Comment: DNS name for ZGallery Dev Backend Service
      TTL: 300
      ResourceRecords:
        - !GetAtt ZGalleryALB.DNSName

  ZGalleryFrontendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      Name: frontend.zgallery.esuarez.info
      HostedZoneName: esuarez.info.
      Comment: DNS name for ZGallery Frontend Service
      TTL: 300
      ResourceRecords:
        - !GetAtt ZGalleryALB.DNSName

  ZGalleryDevFrontendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: CNAME
      Name: frontend.dev.zgallery.esuarez.info
      HostedZoneName: esuarez.info.
      Comment: DNS name for ZGallery Dev Frontend Service
      TTL: 300
      ResourceRecords:
        - !GetAtt ZGalleryALB.DNSName

  ZGalleryPicturesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: zgallery.pictures
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ZGalleryALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'zgallery-alb-sg'
      GroupDescription: 'Allow http for ALB'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ZGalleryERC:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'zgallery-backend'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 10,
              "description": "Keep 3 images only",
              "selection":
              {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
            "action": { "type": "expire" }
            }]
          }

  ZGalleryFrontendERC:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'zgallery-frontend'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 10,
              "description": "Keep 3 images only",
              "selection":
              {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
            "action": { "type": "expire" }
            }]
          }

  ZGalleryALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: zgallery-alb
      SecurityGroups:
        - !GetAtt ZGalleryALBSecurityGroup.GroupId
      Subnets:
        - subnet-0446e35e
        - subnet-5de38815
        - subnet-81e07be7

  ZGalleryALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ZGalleryALBTargetGroup
      LoadBalancerArn: !Ref ZGalleryALB
      Port: 80
      Protocol: HTTP

  ZGalleryRedirectFrontendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ZGalleryALBTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ZGalleryDNS
              - !Ref ZGalleryFrontendDNS
      ListenerArn: !Ref ZGalleryALBListener
      Priority: 20

  ZGalleryRedirectBackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ZGalleryBackendALBTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ZGalleryBackendDNS
      ListenerArn: !Ref ZGalleryALBListener
      Priority: 30

  ZGalleryALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 5000
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-f4c2ec92
      HealthCheckPath: /
      HealthyThresholdCount: 2

  ZGalleryBackendALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-f4c2ec92
      HealthCheckPath: /health-check
      HealthyThresholdCount: 2


Outputs:
  ZGalleryTG:
    Description: ZGallery Target Group
    Value: !Ref ZGalleryALBTargetGroup
    Export:
      Name: zgallery-target-group
  ZGalleryBackendTG:
    Description: ZGallery Backend Target Group
    Value: !Ref ZGalleryBackendALBTargetGroup
    Export:
      Name: zgallery-backend-target-group