version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0
  exported-variables:
    - SAM_CLI_TELEMETRY

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo 'Installing Homebrew...'
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      - test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
      - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
      - echo 'Installing AWS SAM CLI...'
      - brew tap aws/tap
      - brew install aws-sam-cli
      - cd thumbnails_sam
      - echo 'Updating pip...'
      - pip install -U pip
      - echo 'Installing dependencies...'
      - pip install -r build_requirements.txt
  build:
    commands:
      - echo 'Running tests...'
      - pytest -v --disable-warnings
  post_build:
    commands:
      - echo 'Building SAM Applications...'
      - sam build --debug
      - echo 'Packaging SAM Application...'
      - sam package --s3-bucket $BUCKET --output-template-file output-template.yaml --kms-key-id f1e23e0a-9c87-4ae6-98d6-196333ab4256

artifacts:
  type: zip
  files:
    - '**/output-template.yaml'
  discard-paths: yes