version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - cd thumbnails_sam
      - echo 'Installing dependencies...'
      - pip install -r build_requirements.txt
  build:
    commands:
      - echo 'Running tests...'
      - pytest -v --disable-warnings
  post_build:
    commands:
      - echo 'Packaging SAM Application...'
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file output-template.yaml

artifacts:
  type: zip
  files:
    - thumbnals_sam/output-template.yaml