AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Function to create thumbnails

Globals:
  Function:
    Timeout: 3

Resources:
  CreateThumbnailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_thumbnails/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        CreateThumbnailsEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - EC2 Instance State-change Notification

Outputs:
  CreateThumbnailsFunction:
    Description: "CreateThumbnails Lambda Function ARN"
    Value: !GetAtt CreateThumbnailsFunction.Arn
  CreateThumbnailsFunctionIamRole:
    Description: "Implicit IAM Role created for CreateThumbnails function"
    Value: !GetAtt CreateThumbnailsFunctionRole.Arn
