AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Function to create thumbnails

Globals:
  Function:
    Timeout: 60


Resources:
  CreateThumbnailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      FunctionName: create-thumbnails-function
      DeploymentPreference:
        Type: AllAtOnce
      CodeUri: create_thumbnails/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: zgallery.pictures


Outputs:
  CreateThumbnailsFunction:
    Description: "CreateThumbnails Lambda Function ARN"
    Value: !GetAtt CreateThumbnailsFunction.Arn
  CreateThumbnailsFunctionIamRole:
    Description: "Implicit IAM Role created for CreateThumbnails function"
    Value: !GetAtt CreateThumbnailsFunctionRole.Arn
